version: 1.0.{build}
image: Visual Studio 2022

environment:
  nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm test

test_script:
  - npm run coverage

artifacts:
  - path: coverage
    name: code-coverage

stack: node 12

branches:
  only:
    -main

cache: node_modules
install:
  - npm install    
  
build:
  mode: Script
  script: |
    npm install
    npm run lint
    npm run build

test_script:
  - npm run lint && npm test