version: 1.0.{build}
image: Visual Studio 2022

environment:
  nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm run coverage
  - npm run lint && npm test

artifacts:
  - path: coverage
    name: code-coverage

stack: node 12

branches:
  only:
    - main

cache: node_modules  
  
build:
  script:
    - npm install
    - npm run build