version: 1.0.{build}
image: Visual Studio 2022

environment:
  nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - npm run lint
  - npm test

artifacts:
  - path: coverage
    name: code-coverage

branches:
  only:
    - main

cache: node_modules

# Переключение режима сборки на Script и указание команд сборки
build_script:
  - npm install
  - npm run build